package nfv9

type FieldTypeEntry struct {
	Name string
}

var FieldMap = map[int]FieldTypeEntry{
	1:   FieldTypeEntry{Name: "IN_BYTES"},
	2:   FieldTypeEntry{Name: "IN_PKTS"},
	3:   FieldTypeEntry{Name: "FLOWS"},
	4:   FieldTypeEntry{Name: "PROTOCOL"},
	5:   FieldTypeEntry{Name: "SRC_TOS"},
	6:   FieldTypeEntry{Name: "TCP_FLAGS"},
	7:   FieldTypeEntry{Name: "L4_SRC_PORT"},
	8:   FieldTypeEntry{Name: "IPV4_SRC_ADDR"},
	9:   FieldTypeEntry{Name: "SRC_MASK"},
	10:  FieldTypeEntry{Name: "INPUT_SNMP"},
	11:  FieldTypeEntry{Name: "L4_DST_PORT"},
	12:  FieldTypeEntry{Name: "IPV4_DST_ADDR"},
	13:  FieldTypeEntry{Name: "DST_MASK"},
	14:  FieldTypeEntry{Name: "OUTPUT_SNMP"},
	15:  FieldTypeEntry{Name: "IPV4_NEXT_HOP"},
	16:  FieldTypeEntry{Name: "SRC_AS"},
	17:  FieldTypeEntry{Name: "DST_AS"},
	18:  FieldTypeEntry{Name: "BGP_IPV4_NEXT_HOP"},
	19:  FieldTypeEntry{Name: "MUL_DST_PKTS"},
	20:  FieldTypeEntry{Name: "MUL_DST_BYTES"},
	21:  FieldTypeEntry{Name: "LAST_SWITCHED"},
	22:  FieldTypeEntry{Name: "FIRST_SWITCHED"},
	23:  FieldTypeEntry{Name: "OUT_BYTES"},
	24:  FieldTypeEntry{Name: "OUT_PKTS"},
	25:  FieldTypeEntry{Name: "MIN_PKT_LNGTH"},
	26:  FieldTypeEntry{Name: "MAX_PKT_LNGTH"},
	27:  FieldTypeEntry{Name: "IPV6_SRC_ADDR"},
	28:  FieldTypeEntry{Name: "IPV6_DST_ADDR"},
	29:  FieldTypeEntry{Name: "IPV6_SRC_MASK"},
	30:  FieldTypeEntry{Name: "IPV6_DST_MASK"},
	31:  FieldTypeEntry{Name: "IPV6_FLOW_LABEL"},
	32:  FieldTypeEntry{Name: "ICMP_TYPE"},
	33:  FieldTypeEntry{Name: "MUL_IGMP_TYPE"},
	34:  FieldTypeEntry{Name: "SAMPLING_INTERVAL"},
	35:  FieldTypeEntry{Name: "SAMPLING_ALGORITHM"},
	36:  FieldTypeEntry{Name: "FLOW_ACTIVE_TIMEOUT"},
	37:  FieldTypeEntry{Name: "FLOW_INACTIVE_TIMEOUT"},
	38:  FieldTypeEntry{Name: "ENGINE_TYPE"},
	39:  FieldTypeEntry{Name: "ENGINE_ID"},
	40:  FieldTypeEntry{Name: "TOTAL_BYTES_EXP"},
	41:  FieldTypeEntry{Name: "TOTAL_PKTS_EXP"},
	42:  FieldTypeEntry{Name: "TOTAL_FLOWS_EXP"},
	43:  FieldTypeEntry{Name: "*Vendor Proprietary*"},
	44:  FieldTypeEntry{Name: "IPV4_SRC_PREFIX"},
	45:  FieldTypeEntry{Name: "IPV4_DST_PREFIX"},
	46:  FieldTypeEntry{Name: "MPLS_TOP_LABEL_TYPE"},
	47:  FieldTypeEntry{Name: "MPLS_TOP_LABEL_IP_ADDR"},
	48:  FieldTypeEntry{Name: "FLOW_SAMPLER_ID"},
	49:  FieldTypeEntry{Name: "FLOW_SAMPLER_MODE"},
	50:  FieldTypeEntry{Name: "FLOW_SAMPLER_RANDOM_INTERVAL"},
	51:  FieldTypeEntry{Name: "*Vendor Proprietary*"},
	52:  FieldTypeEntry{Name: "MIN_TTL"},
	53:  FieldTypeEntry{Name: "MAX_TTL"},
	54:  FieldTypeEntry{Name: "IPV4_IDENT"},
	55:  FieldTypeEntry{Name: "DST_TOS"},
	56:  FieldTypeEntry{Name: "IN_SRC_MAC"},
	57:  FieldTypeEntry{Name: "OUT_DST_MAC"},
	58:  FieldTypeEntry{Name: "SRC_VLAN"},
	59:  FieldTypeEntry{Name: "DST_VLAN"},
	60:  FieldTypeEntry{Name: "IP_PROTOCOL_VERSION"},
	61:  FieldTypeEntry{Name: "DIRECTION"},
	62:  FieldTypeEntry{Name: "IPV6_NEXT_HOP"},
	63:  FieldTypeEntry{Name: "BGP_IPV6_NEXT_HOP"},
	64:  FieldTypeEntry{Name: "IPV6_OPTIONS_HEADERS"},
	65:  FieldTypeEntry{Name: "*Vendor Proprietary*"},
	66:  FieldTypeEntry{Name: "*Vendor Proprietary*"},
	67:  FieldTypeEntry{Name: "*Vendor Proprietary*"},
	68:  FieldTypeEntry{Name: "*Vendor Proprietary*"},
	69:  FieldTypeEntry{Name: "*Vendor Proprietary*"},
	70:  FieldTypeEntry{Name: "MPLS_LABEL_1"},
	71:  FieldTypeEntry{Name: "MPLS_LABEL_2"},
	72:  FieldTypeEntry{Name: "MPLS_LABEL_3"},
	73:  FieldTypeEntry{Name: "MPLS_LABEL_4"},
	74:  FieldTypeEntry{Name: "MPLS_LABEL_5"},
	75:  FieldTypeEntry{Name: "MPLS_LABEL_6"},
	76:  FieldTypeEntry{Name: "MPLS_LABEL_7"},
	77:  FieldTypeEntry{Name: "MPLS_LABEL_8"},
	78:  FieldTypeEntry{Name: "MPLS_LABEL_9"},
	79:  FieldTypeEntry{Name: "MPLS_LABEL_10"},
	80:  FieldTypeEntry{Name: "IN_DST_MAC"},
	81:  FieldTypeEntry{Name: "OUT_SRC_MAC"},
	82:  FieldTypeEntry{Name: "IF_NAME"},
	83:  FieldTypeEntry{Name: "IF_DESC"},
	84:  FieldTypeEntry{Name: "SAMPLER_NAME"},
	85:  FieldTypeEntry{Name: "IN_PERMANENT_BYTES"},
	86:  FieldTypeEntry{Name: "IN_PERMANENT_PKTS"},
	87:  FieldTypeEntry{Name: "*Vendor Proprietary"},
	88:  FieldTypeEntry{Name: "FRAGMENT_OFFSET"},
	89:  FieldTypeEntry{Name: "FORWARDING_STATUS"},
	90:  FieldTypeEntry{Name: "MPLS_PAL_RD"},
	91:  FieldTypeEntry{Name: "MPLS_PREFIX_LEN"},
	92:  FieldTypeEntry{Name: "SRC_TRAFFIC_INDEX"},
	93:  FieldTypeEntry{Name: "DST_TRAFFIC_INDEX"},
	94:  FieldTypeEntry{Name: "APPLICATION_DESCRIPTION"},
	95:  FieldTypeEntry{Name: "APPLICATION_TAG"},
	96:  FieldTypeEntry{Name: "APPLICATION_NAME"},
	97:  FieldTypeEntry{Name: "postipDiffServCodePoint"},
	98:  FieldTypeEntry{Name: "replication factor"},
	99:  FieldTypeEntry{Name: "DEPRECATED"},
	100: FieldTypeEntry{Name: "layer2packetSectionOffset"},
	101: FieldTypeEntry{Name: "layer2packetSectionSize"},
	102: FieldTypeEntry{Name: "layer2packetSectionData"},
}
